# -*- coding: utf-8 -*-
# Scan to Code - Bone Fracture Detection System (Episode 5)
# Login -> upload DICOM/JPG -> predict -> professional PDF report
# Run:  streamlit run app.py
import os, io, datetime
import numpy as np
import cv2
from PIL import Image
import streamlit as st
from ultralytics import YOLO

# ---------- config ----------
MODEL_PATH = os.path.join(os.path.dirname(os.path.abspath(__file__)), "best.pt")
NAVY = "#0A1628"; CYAN = "#4FD1C5"; ORANGE = "#FF6A3D"

# demo login (for a real app, use a database + hashing)
USERS = {"admin": "scan2code", "doctor": "fracture123"}

st.set_page_config(page_title="Scan to Code - Fracture Detection",
                   page_icon="🦴", layout="wide")


@st.cache_resource
def load_model():
    return YOLO(MODEL_PATH)


# ---------- DICOM / image loading ----------
def load_dicom(file_bytes):
    import pydicom
    ds = pydicom.dcmread(io.BytesIO(file_bytes))
    arr = ds.pixel_array.astype(float)
    arr = (arr - arr.min()) / (arr.max() - arr.min() + 1e-8) * 255.0
    arr = arr.astype(np.uint8)
    if arr.ndim == 2:
        arr = cv2.cvtColor(arr, cv2.COLOR_GRAY2RGB)
    return Image.fromarray(arr)


def load_any(uploaded):
    name = uploaded.name.lower()
    data = uploaded.read()
    if name.endswith(".dcm") or name.endswith(".dicom"):
        return load_dicom(data), "DICOM"
    return Image.open(io.BytesIO(data)).convert("RGB"), "Image"


# ---------- PDF report ----------
def build_pdf(case_id, file_type, detected, n, confs, boxes, input_img, output_img):
    from reportlab.lib.pagesizes import A4
    from reportlab.lib.units import mm
    from reportlab.lib import colors
    from reportlab.platypus import (SimpleDocTemplate, Paragraph, Spacer, Table,
                                    TableStyle, Image as RLImage)
    from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle

    buf = io.BytesIO()
    doc = SimpleDocTemplate(buf, pagesize=A4, topMargin=18 * mm, bottomMargin=15 * mm)
    styles = getSampleStyleSheet()
    navy = colors.HexColor(NAVY); cyan = colors.HexColor(CYAN); orange = colors.HexColor(ORANGE)

    h_title = ParagraphStyle("t", parent=styles["Title"], textColor=navy, fontSize=20)
    h_sub = ParagraphStyle("s", parent=styles["Normal"], textColor=cyan, fontSize=11)
    h_sec = ParagraphStyle("sec", parent=styles["Heading2"], textColor=navy, fontSize=13)
    small = ParagraphStyle("sm", parent=styles["Normal"], fontSize=8, textColor=colors.grey)

    el = []
    el.append(Paragraph("Scan to Code", h_title))
    el.append(Paragraph("Bone Fracture Detection Report", h_sub))
    el.append(Spacer(1, 10))

    # case info
    info = [
        ["Report ID", case_id, "Date", datetime.datetime.now().strftime("%Y-%m-%d %H:%M")],
        ["Input type", file_type, "Model", "YOLO11 Medium"],
    ]
    t = Table(info, colWidths=[70, 150, 60, 150])
    t.setStyle(TableStyle([
        ("BACKGROUND", (0, 0), (0, -1), navy), ("BACKGROUND", (2, 0), (2, -1), navy),
        ("TEXTCOLOR", (0, 0), (0, -1), colors.white), ("TEXTCOLOR", (2, 0), (2, -1), colors.white),
        ("FONTSIZE", (0, 0), (-1, -1), 9), ("GRID", (0, 0), (-1, -1), 0.5, colors.lightgrey),
        ("VALIGN", (0, 0), (-1, -1), "MIDDLE"), ("LEFTPADDING", (0, 0), (-1, -1), 6),
        ("TOPPADDING", (0, 0), (-1, -1), 6), ("BOTTOMPADDING", (0, 0), (-1, -1), 6),
    ]))
    el.append(t); el.append(Spacer(1, 14))

    # result
    el.append(Paragraph("Result", h_sec))
    if detected:
        res = ParagraphStyle("r", parent=styles["Normal"], fontSize=16, textColor=orange, leading=20)
        el.append(Paragraph(f"<b>FRACTURE DETECTED</b> &nbsp; ({n} region{'s' if n > 1 else ''})", res))
        if confs:
            el.append(Paragraph(f"Confidence: {', '.join(str(c) + '%' for c in confs)}", styles["Normal"]))
    else:
        res = ParagraphStyle("r", parent=styles["Normal"], fontSize=16, textColor=colors.green, leading=20)
        el.append(Paragraph("<b>NO FRACTURE DETECTED</b>", res))
    if detected:
        el.append(Paragraph(
            "The fracture region(s) are highlighted with bounding boxes on the "
            "detection image below.", styles["Normal"]))
    el.append(Spacer(1, 14))

    # images
    el.append(Paragraph("Input Scan vs. AI Detection", h_sec))
    el.append(Spacer(1, 6))

    def rl(img, w=240):
        b = io.BytesIO(); img.save(b, format="PNG"); b.seek(0)
        ar = img.height / img.width
        return RLImage(b, width=w, height=w * ar)

    img_tbl = Table([[rl(input_img), rl(output_img)],
                     [Paragraph("Input", small), Paragraph("Detection", small)]],
                    colWidths=[250, 250])
    img_tbl.setStyle(TableStyle([("ALIGN", (0, 0), (-1, -1), "CENTER")]))
    el.append(img_tbl)
    el.append(Spacer(1, 18))

    el.append(Paragraph(
        "DISCLAIMER: This report is generated by an educational AI demonstration and is "
        "NOT a medical device. It must not be used for clinical diagnosis or treatment. "
        "Always consult a qualified radiologist.", small))
    el.append(Spacer(1, 4))
    el.append(Paragraph("Generated by Scan to Code  |  youtube.com/@scantocode", small))

    doc.build(el)
    buf.seek(0)
    return buf.getvalue()


# ---------- LOGIN ----------
def login_screen():
    st.markdown(
        f"<div style='background:{NAVY};padding:28px 32px;border-radius:14px;border-left:10px solid {CYAN};'>"
        f"<h1 style='color:white;margin:0;font-size:36px;'>🦴 Fracture Detection System</h1>"
        f"<p style='color:{CYAN};font-size:21px;margin:8px 0 0 0;font-weight:700;'>"
        f"From medical scan to working AI code &nbsp;|&nbsp; Scan to Code</p></div>",
        unsafe_allow_html=True)
    st.write("")
    st.markdown(f"<h3 style='color:{NAVY};font-size:24px;'>🔐 Please log in to continue</h3>",
                unsafe_allow_html=True)
    with st.form("login"):
        u = st.text_input("Username")
        p = st.text_input("Password", type="password")
        ok = st.form_submit_button("Log in", type="primary")
    if ok:
        if USERS.get(u) == p:
            st.session_state.auth = True
            st.session_state.user = u
            st.rerun()
        else:
            st.error("❌ Invalid username or password.")
    st.info("**Demo login**  —  Username:  `admin`    |    Password:  `scan2code`")


# ---------- MAIN APP ----------
def main_app():
    model = load_model()
    c1, c2 = st.columns([4, 1])
    with c1:
        st.markdown(
            f"<div style='background:{NAVY};padding:18px 26px;border-radius:12px;border-left:10px solid {CYAN};'>"
            f"<h2 style='color:white;margin:0;font-size:30px;'>🦴 Bone Fracture Detection</h2></div>",
            unsafe_allow_html=True)
    with c2:
        st.write("")
        if st.button("🚪 Log out"):
            st.session_state.auth = False
            st.rerun()

    st.markdown(
        f"<p style='color:{NAVY};font-size:19px;font-weight:600;'>"
        f"Welcome, {st.session_state.user} — upload a DICOM or image, then run the detection.</p>",
        unsafe_allow_html=True)
    uploaded = st.file_uploader("Upload an X-ray (DICOM .dcm or JPG / PNG)",
                                type=["dcm", "dicom", "jpg", "jpeg", "png"])

    if uploaded is not None:
        image, ftype = load_any(uploaded)
        if st.button("🔍 Run Prediction", type="primary"):
            results = model.predict(source=np.array(image), verbose=False)[0]
            n = len(results.boxes)
            confs = [round(float(c) * 100) for c in results.boxes.conf] if n else []
            boxes = [list(map(float, b)) for b in results.boxes.xyxy.cpu().numpy()] if n else []
            out_image = Image.fromarray(cv2.cvtColor(results.plot(), cv2.COLOR_BGR2RGB))

            colA, colB = st.columns(2)
            with colA:
                st.subheader("Input Scan"); st.image(image, use_container_width=True)
            with colB:
                st.subheader("AI Detection"); st.image(out_image, use_container_width=True)

            if n > 0:
                st.error(f"⚠️ FRACTURE DETECTED — {n} region(s), confidence: {', '.join(str(c)+'%' for c in confs)}")
            else:
                st.success("✅ No fracture detected.")

            case_id = "SC-" + datetime.datetime.now().strftime("%Y%m%d-%H%M%S")
            pdf = build_pdf(case_id, ftype, n > 0, n, confs, boxes, image, out_image)
            st.download_button("📄 Download PDF Report", data=pdf,
                               file_name=f"{case_id}_fracture_report.pdf", mime="application/pdf")

    st.caption("Educational demo — not a medical device.")


# ---------- ROUTER ----------
if "auth" not in st.session_state:
    st.session_state.auth = False

if st.session_state.auth:
    main_app()
else:
    login_screen()
